server:
  port: 9999

spring:
  application:
    name: mc-gateway
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: http://baidu.com
        predicates:
        - Header=X-Request-Id, \d+
        - Path=/spring-cloud/**
      - id: user
        uri: http://localhost:9001
        predicates:
        - Path=/user/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    appname: gateway-service
    status-page-url-path: /health
