server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: mc-gateway
  cloud:
    gateway:
      locator:
        # 是否从注册中心读取服务
        enabled: true
      routes:
        - id: mc-order
          uri: http://mc-order
          predicates:
          - Header=X-Request-Id, \d+
          - Path=/spring-cloud/**
        - id: mc-user
          uri: http://mc-user
          predicates:
            - Path=/user/**
