server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: mc-gateway
  cloud:
    gateway:
      locator:
        # 是否从注册中心读取服务
        enabled: true
      routes:
        - id: mc-order
          uri: http://mc-order
          predicates:
            - Header=X-Request-Id, \d+
            - Path=/order/**
        - id: mc-user
          uri: lb://mc-user
#          uri: http://localhost:9000
          predicates:
            - Path=/user/**
