server:
  port: 10000

spring:
  application:
    name: mc-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
#   ignored-patterns:
#   - /**/page/**
   # 访问 zuul 的前缀
   # prefix: /api
   # 去掉前缀为 false 默认 true
   # strip-prefix: true
   # 忽略那些服务
   # ignored-services: mc-user
   routes:
     user-service:
       path: /user/**
       serviceId: mc-user
       # sensitiveHeaders: Cookie,Set-Cookie,Authorization
     order-service:
       path: /order/**
       serviceId: mc-order

#ribbon:
#  eureka:
#    enabled: true

#mc-user:
#  ribbon:
#    listOfServers: http://localhost:9001